# Generated by Django 4.2.5 on 2023-12-24 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteForSanta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="What is your name?"),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        default=False, verbose_name="Have you been good this year?"
                    ),
                ),
                (
                    "wishlist",
                    models.TextField(
                        max_length=250,
                        verbose_name="What would you like for Christmas?",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
